'use client';
import { useState } from 'react';
import { ArrowRight, Check, ClipboardCheck, DraftingCompass, Package, Wrench, Settings, Presentation, Flame, HardHat, ShieldCheck, Leaf, Mail, Phone, MapPin, Menu } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet';
const solutions = [
 { name: 'Fire protection systems', image: 'fire', description: 'Hydrants, sprinklers, detection, alarms and suppression.', items: ['Fire audit & consultancy', 'Hydrant & sprinkler systems', 'Detection & alarm systems', 'Suppression systems', 'Fire extinguishers: supply & refilling', 'Fire safety training & signages'] },
 { name: 'Safety & PPE', image: 'ppe', description: 'The equipment and knowledge to protect your people.', items: ['Safety audit & consultancy', 'Personal protective equipment', 'Safety training', 'Safety signages'] },
 { name: 'CCTV surveillance', image: 'cctv', description: 'Practical monitoring solutions for your premises.', items: ['Analog camera systems', 'Digital IP camera systems'] },
 { name: 'Biometric access', image: 'biometric', description: 'Secure, convenient access for authorised personnel.', items: ['Face recognition devices', 'Fingerprint access devices'] },
 { name: 'Environmental audit', image: 'environment', description: 'Expert guidance for a more responsible environment.', items: ['Environmental audit', 'Environmental consultancy'] },
];
const steps = [
 { name: 'Audit', text: 'Understand your risk', icon: ClipboardCheck },
 { name: 'Design', text: 'Plan the right system', icon: DraftingCompass },
 { name: 'Supply', text: 'Source reliable equipment', icon: Package },
 { name: 'Install', text: 'Deliver with precision', icon: Wrench },
 { name: 'Maintain', text: 'Keep systems ready', icon: Settings },
 { name: 'Train', text: 'Prepare your people', icon: Presentation },
];
const navigation = ['Solutions', 'Capabilities', 'Industries', 'About'];
const phones = ['7045143272', '9325505974', '9820818400'];
const phoneLabels = ['+91 70451 43272', '+91 93255 05974', '+91 98208 18400'];
function Brand({ footer = false }: { footer?: boolean }) {
 return <a href="#home" className={`brand ${footer ? 'brand-footer' : ''}`} aria-label="Agniraj home"><img src="/images/agniraj-logo.png" width="704" height="322" alt="Agniraj — Life Secure System India Pvt. Ltd." /></a>;
}
export default function Home() {
 const [contact, setContact] = useState(false);
 const [selected, setSelected] = useState<number | null>(null);
 const [menu, setMenu] = useState(false);
 const service = selected === null ? null : solutions[selected];
 const talk = () => setContact(true);
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <div id="home" className="contact-strip"><div className="container strip-inner"><span><MapPin size={14} /> BKC, Mumbai</span><div><a href="mailto:support@agniraj.in"><Mail size={14} /> support@agniraj.in</a><a href="tel:+917045143272"><Phone size={14} /> +91 70451 43272</a></div></div></div>
 <header className="site-header"><div className="container header-inner"><Brand /><nav aria-label="Main navigation">{navigation.map(n => <a key={n} href={`#${n.toLowerCase()}`}>{n}</a>)}</nav><button className="button header-cta" onClick={talk}>Discuss your requirement <ArrowRight size={18} /></button><button className="menu-button" onClick={() => setMenu(true)} aria-label="Open navigation" aria-expanded={menu}><Menu /></button></div></header>
 <main id="main">
 <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow hero-eyebrow">Fire protection / Safety / Security</p><h1 id="hero-title">Protection that’s<br />built around<br /><em>your risk.</em></h1><p className="hero-description">Complete fire protection and safety solutions for commercial, industrial and residential spaces.</p><div className="hero-actions"><a className="button" href="#solutions">Explore solutions <ArrowRight size={21} /></a><button className="text-button" onClick={talk}>Talk to our team</button></div><div className="hero-promise"><ShieldCheck size={35} strokeWidth={1.3} /><span>Protecting lives. Securing futures.</span></div></div><div className="hero-photo"><img src="/images/engineer.webp" alt="Safety engineer inspecting an overhead sprinkler and fire protection pipework" fetchPriority="high" /><div className="photo-caption">Ready for every day.<br />Prepared for the unexpected.</div></div></section>
 <div className="pillars"><div className="container pillars-inner">{[{ icon: Flame, name: 'Fire protection' }, { icon: HardHat, name: 'Safety & PPE' }, { icon: ShieldCheck, name: 'Security systems' }, { icon: Leaf, name: 'Environmental care' }].map(({icon: Icon,name}) => <div key={name}><Icon size={42} strokeWidth={1.3} /><span>{name}</span></div>)}</div></div>
 <section id="solutions" className="section container"><p className="eyebrow">Our solutions</p><h2>Every layer of protection. One partner.</h2><p className="section-intro">Integrated systems. Expert guidance. Ongoing support.</p><div className="solutions-grid">{solutions.map((s,i) => <button key={s.name} className={`solution-card ${i === 0 ? 'featured' : ''}`} onClick={() => setSelected(i)} aria-label={`Explore ${s.name}`}><div className="card-image"><img src={`/images/${s.image}.webp`} alt="" loading="lazy" /></div><div className="card-copy"><h3><span className="card-number">0{i+1}<b>/</b></span>{s.name}</h3>{i===0 && <p>{s.description}</p>}<ArrowRight className="card-arrow" size={23} strokeWidth={1.4} /></div></button>)}</div></section>
 <section id="capabilities" className="capabilities"><div className="container"><p className="eyebrow">From first audit to long-term support</p><h2>Complete care. At every stage.</h2><ol className="process">{steps.map(({name,text,icon: Icon},i) => <li key={name}><Icon className="process-icon" size={47} strokeWidth={1.25} /><div className="process-track"><span /></div><div className="process-copy"><span className="step-number">0{i+1}</span><h3>{name}</h3><p>{text}</p></div></li>)}</ol></div></section>
 <section id="industries" className="industries"><div className="container industry-layout"><div><p className="eyebrow">Industries we serve</p><h2>Different spaces.<br />The same<br />commitment.</h2></div><div className="industry-cards">{['Commercial','Industrial','Residential'].map(name => <article key={name}><img src={`/images/${name.toLowerCase()}.webp`} alt={`${name} buildings`} loading="lazy" /><h3>{name}</h3></article>)}</div></div></section>
 <section id="about" className="about container"><div className="about-photo"><img src="/images/engineer.webp" alt="Fire protection engineer conducting an inspection" loading="lazy" /></div><div className="about-copy"><p className="eyebrow">About Agniraj</p><h2>Engineered readiness.<br />Built on integrity.</h2><p>We bring fire protection, safety and security together to help organisations create safer environments. From consultation and installation to maintenance and training, our team supports the full lifecycle of your systems.</p><div className="values">{['Quality assured', 'Safety first', 'Expert team'].map(v => <span key={v}><Check size={22} />{v}</span>)}</div></div></section>
 <section className="cta-band"><div className="container cta-inner"><div><h2>Let’s make your facility safer.</h2><p>Start with a conversation about your requirements.</p></div><button className="button button-white" onClick={talk}>Talk to our team <ArrowRight size={23} /></button></div></section>
 </main>
 <footer><div className="container footer-grid"><div><Brand footer /><p className="footer-tagline">Protecting lives.<br />Securing futures.</p></div><div><h3>Explore</h3>{navigation.map(n => <a href={`#${n.toLowerCase()}`} key={n}>{n}</a>)}<button onClick={talk}>Contact</button></div><div><h3>Solutions</h3>{solutions.map((s,i) => <button onClick={() => setSelected(i)} key={s.name}>{s.name}</button>)}</div><div className="footer-contact"><h3>Get in touch</h3><a href="mailto:support@agniraj.in"><Mail size={17} />support@agniraj.in</a>{phones.map((p,i) => <a key={p} href={`tel:+91${p}`}><Phone size={16} />{phoneLabels[i]}</a>)}<p><MapPin size={18} /><span>B-04A, Balarama Bldg, E-Block,<br />BKC, Bandra (E), Mumbai 400051</span></p></div></div><div className="container footer-bottom">© {new Date().getFullYear()} Agniraj Life Secure Systems India Pvt. Ltd. All rights reserved.</div></footer>
 <Sheet open={menu} onOpenChange={setMenu}><SheetContent className="mobile-sheet"><SheetTitle>Explore Agniraj</SheetTitle><SheetDescription>Fire protection, safety and security.</SheetDescription><nav aria-label="Mobile navigation">{navigation.map(n => <a key={n} href={`#${n.toLowerCase()}`} onClick={() => setMenu(false)}>{n}<ArrowRight size={19} /></a>)}</nav><button className="button" onClick={() => { setMenu(false); talk(); }}>Discuss your requirement <ArrowRight size={18} /></button></SheetContent></Sheet>
 <Dialog open={selected !== null} onOpenChange={open => { if(!open) setSelected(null); }}><DialogContent className="service-dialog"><p className="eyebrow">Our solutions</p><DialogTitle>{service?.name}</DialogTitle><DialogDescription>{service?.description}</DialogDescription><ul className="service-list">{service?.items.map(item => <li key={item}><Check size={19} />{item}</li>)}</ul><button className="button" onClick={() => { setSelected(null); talk(); }}>Discuss your requirement <ArrowRight size={18} /></button></DialogContent></Dialog>
 <Dialog open={contact} onOpenChange={setContact}><DialogContent className="contact-dialog"><p className="eyebrow">Let’s talk safety</p><DialogTitle>Tell us what you need.</DialogTitle><DialogDescription>Contact our team for enquiries, consultations or service requirements.</DialogDescription><a className="contact-email" href="mailto:support@agniraj.in?subject=Website%20enquiry"><Mail size={23} /><span><small>Email our team</small>support@agniraj.in</span><ArrowRight size={20} /></a><div className="contact-phones">{phones.map((p,i) => <a key={p} href={`tel:+91${p}`}><Phone size={19} />{phoneLabels[i]}<ArrowRight size={18} /></a>)}</div><p className="contact-address"><MapPin size={20} /><span>B-04A, Balarama Bldg, E-Block,<br />BKC, Bandra (E), Mumbai 400051</span></p></DialogContent></Dialog>
 </>;
}
